"use client";

import { useId, useMemo, useState } from "react";
import { Boxes, FolderTree, Focus, Minus, Plus, ArrowRight, Network } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AskButton } from "@/components/ask-codandy";
import { architectureMap } from "@/lib/architecture-map";
import type { AnalysisAtlas } from "@/lib/analysis-api";

export function ArchitectureMap({ atlas, onInspect }: { atlas: AnalysisAtlas; onInspect: (id: string) => void }) {
  const [mode, setMode] = useState<"folders" | "projects">("folders");
  const [depth, setDepth] = useState(1);
  const [query, setQuery] = useState("");
  const [focus, setFocus] = useState<string | null>(null);
  const [zoom, setZoom] = useState(1);
  const marker = useId().replaceAll(":", "");
  const graph = useMemo(() => architectureMap(atlas, mode, depth), [atlas, mode, depth]);
  const byId = useMemo(() => new Map(atlas.nodes.map(node => [node.id, node])), [atlas]);
  const adjacent = new Set(graph.links.filter(link => link.source === focus || link.target === focus).flatMap(link => [link.source, link.target]));
  const eligible = graph.groups.filter(group => group.label.toLowerCase().includes(query.toLowerCase()) && (!focus || group.id === focus || adjacent.has(group.id)));
  const ordered = focus ? [...eligible.filter(group => group.id === focus), ...eligible.filter(group => group.id !== focus)] : eligible;
  const visible = ordered.slice(0, 10);
  const ids = new Set(visible.map(group => group.id));
  const links = graph.links.filter(link => ids.has(link.source) && ids.has(link.target));
  const positions = new Map(visible.map((group, i) => {
    const angle = -Math.PI / 2 + i * Math.PI * 2 / visible.length;
    return [group.id, { x: visible.length === 1 ? 500 : 500 + Math.cos(angle) * 365, y: visible.length === 1 ? 330 : 330 + Math.sin(angle) * 255 }];
  }));
  const selected = graph.groups.find(group => group.id === focus);
  const relevant = focus ? graph.links.filter(link => link.source === focus || link.target === focus) : links;
  function changeMode(value: "folders" | "projects") { setMode(value); setFocus(null); setQuery(""); }
  return <section className="overflow-hidden rounded-2xl border border-white/10 bg-[var(--surface-4)]" aria-label="Interactive architecture map">
    <div className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 p-5 sm:p-6"><div><p className="flex items-center gap-2 text-xs font-medium uppercase tracking-widest text-cyan-300"><Network className="size-4" />Architecture map</p><h3 className="mt-2 text-xl font-semibold">See the dependencies between {mode === "folders" ? "source areas" : "projects"}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Arrows point from the importer to its dependency. Select a group to focus its neighbors and inspect the underlying evidence.</p></div><AskButton scope={{ title: "Architecture dependency map", nodeIds: (selected?.nodeIds || visible.flatMap(group => group.nodeIds)).slice(0, 24), notes: "Static dependency map; folder grouping is based on source paths, not verified runtime services." }}>Ask about this map</AskButton></div>
    <div className="flex flex-wrap items-center gap-3 p-4"><div className="flex gap-1 rounded-lg border border-white/10 p-1"><Button size="sm" variant={mode === "folders" ? "secondary" : "ghost"} aria-pressed={mode === "folders"} onClick={() => changeMode("folders")}><FolderTree className="size-4" />Source areas</Button><Button size="sm" variant={mode === "projects" ? "secondary" : "ghost"} aria-pressed={mode === "projects"} onClick={() => changeMode("projects")}><Boxes className="size-4" />Projects</Button></div>{mode === "folders" && <label className="flex items-center gap-2 text-xs text-slate-400">Folder depth<select className="rounded-lg border border-white/10 bg-card p-2" value={depth} onChange={e => { setDepth(Number(e.target.value)); setFocus(null); }}><option value={1}>1 level</option><option value={2}>2 levels</option><option value={3}>3 levels</option></select></label>}<Input className="min-w-40 flex-1" aria-label="Find architecture group" placeholder="Find a source area…" value={query} onChange={e => { setQuery(e.target.value); setFocus(null); }} /><div className="flex gap-1"><Button variant="ghost" size="icon" aria-label="Zoom out architecture map" disabled={zoom <= 0.6} onClick={() => setZoom(value => Math.max(0.6, value - 0.2))}><Minus /></Button><Button variant="ghost" size="icon" aria-label="Zoom in architecture map" disabled={zoom >= 1.8} onClick={() => setZoom(value => Math.min(1.8, value + 0.2))}><Plus /></Button><Button variant="ghost" size="icon" aria-label="Reset architecture map" onClick={() => { setFocus(null); setQuery(""); setZoom(1); }}><Focus /></Button></div></div>
    {!visible.length ? <p className="p-8 text-slate-400">{graph.groups.length ? "No groups match this search." : "No supported projects were detected. Switch to Source areas to explore indexed files."}</p> : <><div className="space-y-3 border-y border-white/[0.06] bg-[var(--background)] p-4 sm:hidden" aria-label="Mobile dependency diagram"><p className="text-xs text-slate-400">Select an area or follow an arrow to explore its dependencies.</p><div className="flex flex-wrap gap-2">{visible.map(group => <button key={group.id} aria-pressed={focus === group.id} onClick={() => setFocus(focus === group.id ? null : group.id)} className={`rounded-lg border px-3 py-2 text-left text-xs ${focus === group.id ? "border-cyan-300/50 text-cyan-200" : "border-white/10 text-slate-300"}`}>{group.label}<span className="mt-1 block text-slate-500">{group.nodeIds.length} {mode === "folders" ? "files" : "project"}</span></button>)}</div>{links.map(link => <div key={`${link.source}:${link.target}`} className={`rounded-xl border bg-[var(--surface-4)] p-3 ${link.inferred ? "border-amber-300/20" : "border-cyan-300/20"}`}><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><button className="break-all text-left text-sm" onClick={() => setFocus(link.source)}>{graph.groups.find(group => group.id === link.source)?.label}</button><ArrowRight aria-label="depends on" className={`size-4 ${link.inferred ? "text-amber-300" : "text-cyan-300"}`} /><button className="break-all text-right text-sm" onClick={() => setFocus(link.target)}>{graph.groups.find(group => group.id === link.target)?.label}</button></div><p className="mt-2 text-xs text-slate-500">{link.count} relationships · {link.inferred ? "includes inferred" : "resolved"}</p></div>)}{!links.length && <p className="text-sm text-slate-500">No supported connections in this view.</p>}</div><div className="hidden overflow-auto border-y border-white/[0.06] bg-[var(--background)] p-3 sm:block" tabIndex={0} aria-label="Scrollable dependency diagram"><svg viewBox="0 0 1000 670" role="group" aria-label={`${mode} dependency diagram`} style={{ width: `${zoom * 100}%`, minWidth: `${650 * zoom}px` }} className="mx-auto max-h-none">
      <defs><marker id={marker} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke" /></marker></defs>
      <circle cx="500" cy="330" r="125" fill="none" stroke="currentColor" className="text-slate-500/10" strokeDasharray="4 8" />
      <text x="500" y="323" textAnchor="middle" fill="currentColor" className="fill-slate-500 text-[13px]">STATIC DEPENDENCIES</text><text x="500" y="348" textAnchor="middle" fill="currentColor" className="fill-slate-400 text-[12px]">{links.length} visible connections</text>
      {links.map(link => { const start = positions.get(link.source)!, end = positions.get(link.target)!; const dx = end.x - start.x, dy = end.y - start.y; const distance = Math.hypot(dx, dy); const trim = Math.min(95 / Math.max(Math.abs(dx / distance), 0.01), 42 / Math.max(Math.abs(dy / distance), 0.01)); const x = end.x - dx / distance * trim, y = end.y - dy / distance * trim; return <path key={`${link.source}:${link.target}`} d={`M ${start.x} ${start.y} Q ${500 + dy * 0.12} ${330 - dx * 0.12} ${x} ${y}`} fill="none" stroke="currentColor" className={link.inferred ? "text-amber-300/50" : "text-cyan-300/45"} strokeWidth={Math.min(5, 1.3 + Math.log2(link.count + 1))} strokeDasharray={link.inferred ? "7 5" : undefined} markerEnd={`url(#${marker})`}><title>{graph.groups.find(group => group.id === link.source)?.label} → {graph.groups.find(group => group.id === link.target)?.label}: {link.count} relationships, {link.inferred} inferred</title></path>; })}
      {visible.map(group => { const { x, y } = positions.get(group.id)!; const active = focus === group.id; return <g key={group.id} role="button" tabIndex={0} aria-label={`${group.label}, ${group.nodeIds.length} ${mode === "folders" ? "files" : "project"}; focus dependencies`} aria-pressed={active} onClick={() => setFocus(active ? null : group.id)} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); setFocus(active ? null : group.id); } }} className="cursor-pointer outline-none [&:focus_rect]:stroke-white"><title>{group.label}</title><rect x={x - 96} y={y - 39} width="192" height="78" rx="14" fill="var(--surface-4)" stroke={active ? "var(--primary)" : "var(--border)"} strokeWidth={active ? "2.5" : "1.5"} /><rect x={x - 96} y={y - 19} width="3" height="38" rx="1.5" fill="var(--primary)" /><text x={x} y={y - 7} textAnchor="middle" fill="var(--foreground)" fontSize="14" fontWeight="600">{group.label.length > 23 ? `${group.label.slice(0, 20)}…` : group.label}</text><text x={x} y={y + 16} textAnchor="middle" fill="var(--muted-foreground)" fontSize="11">{group.nodeIds.length} {mode === "folders" ? "source files" : "project"} · {group.internal} internal links</text></g>; })}
    </svg></div></>}
    <div className="flex flex-wrap gap-x-5 gap-y-2 px-5 py-3 text-xs text-slate-400"><span className="text-cyan-300">━ Resolved</span><span className="text-amber-300">┄ Includes inferred links</span><span>Thicker lines = more relationships</span><span>{visible.length}/{graph.groups.length} groups · {graph.links.length - links.length} connections outside view · {mode === "projects" ? `${graph.unresolved} unresolved project references omitted` : graph.classified ? `${graph.unresolved} unresolved local imports · ${graph.external} package, standard-library or namespace imports not drawn` : `${graph.external} imports without a resolved local target not drawn (reanalyze to separate packages from unresolved local imports)`}</span></div>
    <div className="grid gap-5 border-t border-white/10 p-5 lg:grid-cols-2"><div><h4 className="font-medium">{selected ? selected.label : "Explore a source area"}</h4><p className="mt-2 text-sm leading-6 text-slate-400">{selected ? "Open a captured node below, or choose a connection to focus its source group." : "The map shows up to ten groups, ranked by dependency activity. Search or select a group to reduce visual clutter. Folder names do not establish architectural layers or runtime services."}</p>{selected && <div className="mt-3 max-h-52 space-y-1 overflow-auto">{selected.nodeIds.slice(0, 40).map(id => <button key={id} className="block w-full break-all rounded-lg p-2 text-left text-xs text-cyan-200 hover:bg-white/5" onClick={() => onInspect(id)}>{byId.get(id)?.path || byId.get(id)?.label}</button>)}{selected.nodeIds.length > 40 && <p className="text-xs text-slate-500">First 40 locations shown. Use Codebase to inspect the complete inventory.</p>}</div>}</div><div><h4 className="font-medium">{selected ? "Connected groups" : "Visible connections"}</h4><div className="mt-3 max-h-60 space-y-2 overflow-auto">{relevant.slice(0, 30).map(link => <div key={`${link.source}:${link.target}`} className="rounded-lg border border-white/[0.07] p-3"><button className="flex w-full items-center gap-2 text-left text-xs text-slate-300" onClick={() => { setFocus(link.source); setQuery(""); }}><span className="min-w-0 flex-1 break-all">{graph.groups.find(group => group.id === link.source)?.label}</span><ArrowRight className="size-3 shrink-0 text-cyan-300" /><span className="min-w-0 flex-1 break-all">{graph.groups.find(group => group.id === link.target)?.label}</span></button><div className="mt-2 flex items-center justify-between gap-2 text-xs text-slate-500"><span>{link.count} links · {link.inferred} inferred</span><button className="text-cyan-200 hover:underline" onClick={() => onInspect(link.nodeIds[0])}>Inspect evidence</button></div></div>)}{!relevant.length && <p className="text-sm text-slate-500">No supported connections for this view. Disconnected groups remain visible; unresolved relationships are not filled in.</p>}</div></div></div>
  </section>;
}
